name: Report a bug
description: Request a bug fix.
assignees:
  - samggeer
labels:
  - action: fix
  - stage: concept
  
body:

  - type: markdown
    attributes:
      value: |
        Before opening a **Bug Report**, please search for the behavior in the existing issues.        
        
        * Found a security flaw? Submit a [**Vulnerability Report**](https://lightlystyled.com/contact).
        * Need real-time help? Join the [**Discussions**](https://github.com/orgs/LightlyStyled/discussions).

        ---
  
  - type: dropdown
    id: affected-packages
    attributes:
      label: Bug source
      description: Where is the bug?
      options:
        - Less Skin
        - Less Changelogs Box
        - Less Definitions Box
        - Less Documents Box
        - Less Events Box
        - Less Press Box
        - Less Questions Box
        - Less Testimonials Box
        - Less Updates Box
      multiple: false
    validations:
      required: true
      
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug type
      description: What type of bug is it?
      options:
        - Transient - Occurs only once
        - Intermittent - Occurs irregularly
        - Permanent - Occurs repeatably
      multiple: false
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Bug reproduction
      description: How did you find the bug?
      placeholder: |
        1. Go to...
        2. Select...
        3. Scroll to...
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Bug behavior
      description: What happened when you found the bug?
      placeholder: |
        I expected [some behavior] to happen, but instead [some other behavior] happened.
    validations:
      required: true
  
  - type: textarea
    id: log
    attributes:
      label: System status log
      description: Provide the thesis system status log.
      render: true
      placeholder: |
        Thesis & Current Skin
        ===========================
        Thesis Version: 2.x.x
        Skin Name: Less
        Skin Version: x.x.x
        Skin CSS: YES → xx.xkB on 01/01/2000 at 24:00:00
        Skin Custom CSS: YES → x.x8kB
        Skin Custom PHP: YES → 0.xkB on 01/01/2000 at 24:00:00
        ...etc.
    validations:
        required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Is there anything else you can share?
