name: Suggest an idea
description: Request a new feature.
assignees:
  - samggeer
labels:
  - action: feat
  - stage: concept

body:

  - type: markdown
    attributes:
      value: |
        Before requesting a **New Feature**, please search for the feature in the existing issues.        
        
        * Found a security flaw? Submit a [**Vulnerability Report**](https://lightlystyled.com/contact).
        * Need real-time help? Join the [**Discussions**](https://github.com/orgs/LightlyStyled/discussions).

        ---

  - type: dropdown
    id: affected-packages
    attributes:
      label: Feature package
      description: What package is relevant to the feature?
      options:
        - Less Skin
        - Less Changelogs Box
        - Less Definitions Box
        - Less Documents Box
        - Less Events Box
        - Less Press Box
        - Less Questions Box
        - Less Testimonials Box
        - Less Updates Box
      multiple: false
 
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What problem will the feature solve?
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: What is your proposed solution?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Is there anything else you can share?
